[package]
name = "serenaluo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rdkafka = "0.36.2"

tokio = {version = "1.36.0", features =["full"]}
